--- # Tasks that can be done in any distro belong here

#
# Installs SSH Keys
#
- name: Installs authorized key
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', './id_rsa.pub') }}"
- name: Copy id_rsa file to .ssh/
  copy:
    src: ./id_rsa
    dest: /home/{{ user }}/.ssh/id_rsa
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0600'
- name: Copy id_rsa.pub file to .ssh/
  copy:
    src: ./id_rsa.pub
    dest: /home/{{ user }}/.ssh/id_rsa.pub
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0600'

#
# Service configuration
#
- name: Disable password SSH login
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
    state=present
  notify: restart ssh
- name: Disable root SSH access
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin"
    line="PermitRootLogin no"
    state=present
  notify: restart ssh
- name: Mask ctrl-alt-del.target
  systemd:
    name: ctrl-alt-del.target
    masked: yes
    enabled: no
    daemon_reload: yes