--- # Playbook for Red Hat and CentOS servers

#
# Set up Docker and docker-compose
#
- name: Update all packages [Red Hat/CentOS]
  yum:
    name: '*'
    state: latest
- name: Install new packages for docker pre-reqs (Red Hat/CentOS)
  yum:
    name:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    state: latest
- name: Add the Docker repository (Red Hat/CentOS)
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
- name: Install Docker (Red Hat/CentOS)
  yum:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/local/bin/docker-compose      
    mode: '0755'
- name: Start Docker service
  service:
    name: docker
    enabled: yes
    state: started

#
# Configure user account
#
- name: Adding user account
  user:
    name: "{{ user }}" 
    groups: docker,wheel
    create_home: yes
    shell: /bin/bash
    skeleton: /etc/skel
  notify: password setup

#
# Additional package installation
#
- name: Install additional packages (Red Hat/CentOS)
  yum:
    name:
    - fail2ban
    - git
    state: latest