--- # Playbook for Ubuntu servers

#
# Set up Docker and docker-compose
#
- name: Update all packages (Ubuntu)
  apt:
    name: '*'
    state: latest
    force_apt_get: yes
- name: Install new packages for docker pre-reqs (Ubuntu)
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - wget
    - gnupg-agent
    - software-properties-common
    state: latest
    force_apt_get: yes
- name: Add Docker GPG key (Ubuntu)
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add the Docker repository (Ubuntu)
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker (Ubuntu)
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    force_apt_get: yes
- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/local/bin/docker-compose      
    mode: '0755'
- name: Start Docker service
  service:
    name: docker
    enabled: yes
    state: started

#
# Configure user account
#
- name: Adding user account
  user:
    name: "{{ user }}" 
    groups: docker,sudo
    create_home: yes
    shell: /bin/bash
    skeleton: /etc/skel
  notify: password setup

#
# Additional package installation
#
- name: Install additional packages (Ubuntu)
  apt:
    name:
    - fail2ban
    - git
    state: latest
    force_apt_get: yes